# Generated by Django 6.0.6 on 2026-07-09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_conference_denomination"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="financials_provisioned",
            field=models.BooleanField(
                default=False,
                help_text="True after denomination/default financial seeds have been applied.",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive churches are hidden from operations and user assignment.",
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["conference", "code"], name="org_zone_conf_code_idx"),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["zone", "code"], name="org_dist_zone_code_idx"),
        ),
        migrations.AddIndex(
            model_name="church",
            index=models.Index(fields=["district", "code"], name="org_church_dist_code_idx"),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                fields=("conference", "code"),
                name="uniq_zone_code_per_conference",
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("zone", "code"),
                name="uniq_district_code_per_zone",
            ),
        ),
        migrations.AddConstraint(
            model_name="church",
            constraint=models.UniqueConstraint(
                fields=("district", "code"),
                name="uniq_church_code_per_district",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DEACTIVATE", "Deactivate"),
                            ("ACTIVATE", "Activate"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.UUIDField()),
                ("entity_label", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="organization_audit_actions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
