# Generated by Django 5.1.15 on 2026-07-24 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_backfill_financials_provisioned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Narrative details preserved for future reference.')),
                ('event_date', models.DateField(help_text='When this history event occurred (or best known date).')),
                ('category', models.CharField(choices=[('FOUNDING', 'Founding'), ('BUILDING', 'Building / Facility'), ('PASTORATE', 'Pastorate'), ('LEADERSHIP', 'Leadership'), ('MILESTONE', 'Milestone'), ('EVENT', 'Special Event'), ('OTHER', 'Other')], db_index=True, default='MILESTONE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Optional keywords for search (comma-separated).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='organization.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_history_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_history_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'church history entry',
                'verbose_name_plural': 'church history entries',
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['church', '-event_date'], name='org_chhist_church_date_idx'), models.Index(fields=['category', '-event_date'], name='org_chhist_cat_date_idx')],
            },
        ),
    ]
