# Generated by Django 5.1.15 on 2026-07-30 02:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_member_portal_email_unique_and_dob'),
        ('organization', '0006_church_history_entry'),
        ('transactions', '0020_treasury_receipt_auto_approve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=40)),
                ('purpose', models.TextField(blank=True, default='', help_text='Shown to members on the portal — describe why this drive exists.')),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional church-wide fundraising goal.', max_digits=14, null=True)),
                ('portal_visible', models.BooleanField(default=True, help_text='When open, show this campaign on the member portal.')),
                ('show_church_progress', models.BooleanField(default=True, help_text='Members may see church-wide totals and progress on the portal.')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_campaigns', to='organization.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('offering_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_campaigns', to='transactions.offeringcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_campaigns_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deadline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contribution_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.contributioncampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contributions', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_contributions_recorded', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_contributions', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-contribution_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contributioncampaign',
            index=models.Index(fields=['church', 'status'], name='contributio_church__07f438_idx'),
        ),
        migrations.AddIndex(
            model_name='contributioncampaign',
            index=models.Index(fields=['church', 'deadline'], name='contributio_church__d8e7c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributioncampaign',
            unique_together={('church', 'code')},
        ),
        migrations.AddIndex(
            model_name='membercontribution',
            index=models.Index(fields=['campaign', 'member'], name='contributio_campaig_7f6bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='membercontribution',
            index=models.Index(fields=['campaign', 'contribution_date'], name='contributio_campaig_9076ac_idx'),
        ),
        migrations.AddIndex(
            model_name='membercontribution',
            index=models.Index(fields=['member', 'contribution_date'], name='contributio_member__429fff_idx'),
        ),
    ]
