# Generated by Django 5.1.15 on 2026-07-30 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('members', '0008_member_portal_email_unique_and_dob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributioncampaign',
            name='default_member_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional default pledge/target amount suggested for each member.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contributioncampaign',
            name='send_email_reminders',
            field=models.BooleanField(default=True, help_text='Send deadline reminder emails to portal members when SMTP is configured.'),
        ),
        migrations.CreateModel(
            name='CampaignDeadlineReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_key', models.CharField(max_length=16)),
                ('notification_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reminders', to='contributions.contributioncampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_deadline_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'reminder_key'], name='contributio_campaig_8c2f29_idx')],
                'unique_together': {('campaign', 'user', 'reminder_key')},
            },
        ),
        migrations.CreateModel(
            name='MemberCampaignTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_targets', to='contributions.contributioncampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_campaign_targets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'member'], name='contributio_campaig_b42013_idx')],
                'unique_together': {('campaign', 'member')},
            },
        ),
    ]
