# Generated by Django 6.0.6 on 2026-07-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='remittancepolicy',
            new_name='remittance__unit_ty_3396d9_idx',
            old_name='remittance__unit_ty_8a0f0d_idx',
        ),
    ]
