# Generated by Django 6.0.6 on 2026-07-08 22:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _backfill_welfare_data(apps, schema_editor):
    WelfareAssistanceCase = apps.get_model("remittance", "WelfareAssistanceCase")
    year = 2026
    counters = {}
    for case in WelfareAssistanceCase.objects.order_by("created_at"):
        if case.case_number:
            continue
        yr = case.created_at.year if case.created_at else year
        key = (case.church_id, yr)
        counters[key] = counters.get(key, 0) + 1
        case.case_number = f"WEL-{yr}-{counters[key]:04d}"
        case.save(update_fields=["case_number"])

    from remittance.welfare_services import backfill_welfare_ledger

    backfill_welfare_ledger()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_leadershiprole_spiritualgift_memberspiritualgift'),
        ('organization', '0003_conference_denomination'),
        ('remittance', '0002_rename_remittance__unit_ty_8a0f0d_idx_remittance__unit_ty_3396d9_idx'),
        ('transactions', '0011_welfare_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareCaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to='welfare/cases/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareMemberLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('REQUEST', 'Assistance Request'), ('DISBURSEMENT', 'Disbursement'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='welfareassistancecase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='welfarecontribution',
            options={'ordering': ['-contribution_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='assistance_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('BEREAVEMENT', 'Bereavement'), ('EDUCATION', 'Education'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_cases_disbursed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='disbursement_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_assistance_cases', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfareassistancecase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_cases_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfarecontribution',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Contribution recorded without a named member.'),
        ),
        migrations.AlterField(
            model_name='welfareassistancecase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=14),
        ),
        migrations.AddIndex(
            model_name='welfareassistancecase',
            index=models.Index(fields=['church', 'status'], name='remittance__church__17023f_idx'),
        ),
        migrations.AddIndex(
            model_name='welfareassistancecase',
            index=models.Index(fields=['member', 'status'], name='remittance__member__55820c_idx'),
        ),
        migrations.AddIndex(
            model_name='welfarecontribution',
            index=models.Index(fields=['church', 'contribution_date'], name='remittance__church__ab35c3_idx'),
        ),
        migrations.AddIndex(
            model_name='welfarecontribution',
            index=models.Index(fields=['member', 'contribution_date'], name='remittance__member__5fc57c_idx'),
        ),
        migrations.AddConstraint(
            model_name='welfareassistancecase',
            constraint=models.UniqueConstraint(fields=('church', 'case_number'), name='remittance_welfare_case_number_unique'),
        ),
        migrations.AddField(
            model_name='welfarecaseattachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='remittance.welfareassistancecase'),
        ),
        migrations.AddField(
            model_name='welfarecaseattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfarememberledger',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='remittance.welfareassistancecase'),
        ),
        migrations.AddField(
            model_name='welfarememberledger',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_ledger_entries', to='organization.church'),
        ),
        migrations.AddField(
            model_name='welfarememberledger',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='remittance.welfarecontribution'),
        ),
        migrations.AddField(
            model_name='welfarememberledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_ledger_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfarememberledger',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_ledger_entries', to='members.member'),
        ),
        migrations.AddField(
            model_name='welfarememberledger',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_ledger_entries', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='welfarememberledger',
            index=models.Index(fields=['church', 'member', 'entry_date'], name='remittance__church__50d2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='welfarememberledger',
            index=models.Index(fields=['member', 'entry_type'], name='remittance__member__b79f30_idx'),
        ),
        migrations.RunPython(_backfill_welfare_data, migrations.RunPython.noop),
    ]
