# Generated by Django 5.1.15 on 2026-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0003_welfare_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittancepolicyauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DEACTIVATE', 'Deactivated'), ('SCOPE_VIOLATION', 'Scope violation')], max_length=20),
        ),
    ]
