# Generated by Django 5.1.15 on 2026-09-10 14:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('organization', '0006_church_history_entry'),
        ('sitecontrol', '0025_activation_request_requested_plan'),
        ('transactions', '0023_transaction_reversed_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('block_auto_approve_on_high', models.BooleanField(default=False, help_text='Reserved. Receipt auto-approve is never blocked by this flag.')),
                ('large_multiplier', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8)),
                ('large_absolute', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14)),
                ('large_min_sample', models.PositiveSmallIntegerField(default=8)),
                ('near_duplicate_minutes', models.PositiveIntegerField(default=15)),
                ('near_duplicate_min_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14)),
                ('repeat_count', models.PositiveSmallIntegerField(default=5)),
                ('repeat_hours', models.PositiveIntegerField(default=24)),
                ('expense_absolute', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14)),
                ('reversal_count', models.PositiveSmallIntegerField(default=3)),
                ('reversal_days', models.PositiveIntegerField(default=7)),
                ('velocity_count', models.PositiveSmallIntegerField(default=30)),
                ('velocity_minutes', models.PositiveIntegerField(default=60)),
                ('step_change_ratio', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=8)),
                ('bunching_last_days', models.PositiveSmallIntegerField(default=3)),
                ('bunching_share', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('bunching_min_count', models.PositiveSmallIntegerField(default=6)),
                ('baseline_min_sample', models.PositiveSmallIntegerField(default=10)),
                ('baseline_z', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=6)),
                ('lookback_days', models.PositiveIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_policy', to='organization.church')),
            ],
            options={
                'verbose_name': 'Financial risk policy',
                'verbose_name_plural': 'Financial risk policies',
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=16)),
                ('fingerprint', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('observed', models.JSONField(blank=True, default=dict)),
                ('threshold', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('approval_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='approvals.approvalcase')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='organization.church')),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='sitecontrol.denomination')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_risk_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['church', 'status', 'severity'], name='intelligenc_church__0bb418_idx'), models.Index(fields=['church', 'rule_code'], name='intelligenc_church__7fd790_idx')],
                'constraints': [models.UniqueConstraint(fields=('church', 'rule_code', 'fingerprint'), name='intelligence_alert_idempotent')],
            },
        ),
    ]
