# Generated by Django 6.0.6 on 2026-07-04 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('transactions', '0003_transaction_is_voided_transaction_reversal_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('default_narration', models.CharField(blank=True, help_text='Suggested narration when this category is selected.', max_length=200)),
                ('requires_member', models.BooleanField(default=False, help_text='Member must be linked for member-specific receipts (e.g. tithe).')),
                ('remit_to_district', models.BooleanField(default=False, help_text='Include in district remittance totals when applicable.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_categories', to='organization.church')),
                ('default_credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_credit_categories', to='transactions.account')),
                ('default_debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_debit_categories', to='transactions.account')),
            ],
            options={
                'verbose_name_plural': 'Ledger categories',
                'ordering': ['transaction_type', 'sort_order', 'name'],
                'unique_together': {('church', 'code')},
            },
        ),
    ]
