# Generated by Django 6.0.6 on 2026-07-07 02:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_leadershiprole_spiritualgift_memberspiritualgift'),
        ('organization', '0002_generalconference_union_conference_union'),
        ('transactions', '0008_alter_account_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategoryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('gra_asset_class', models.CharField(choices=[('1', 'Class 1 — Buildings & structures'), ('2', 'Class 2 — Vehicles, plant & heavy equipment'), ('3', 'Class 3 — IT, office equipment, fixtures'), ('4', 'Class 4 — Low-value / short-life items')], default='3', max_length=1)),
                ('default_useful_life_months', models.PositiveIntegerField(default=48)),
                ('default_depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line'), ('DECLINING_BALANCE', 'Declining balance (150% DB)')], default='STRAIGHT_LINE', max_length=20)),
                ('default_salvage_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('gra_asset_class', models.CharField(choices=[('1', 'Class 1 — Buildings & structures'), ('2', 'Class 2 — Vehicles, plant & heavy equipment'), ('3', 'Class 3 — IT, office equipment, fixtures'), ('4', 'Class 4 — Low-value / short-life items')], default='3', max_length=1)),
                ('useful_life_months', models.PositiveIntegerField(default=48)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line'), ('DECLINING_BALANCE', 'Declining balance (150% DB)')], default='STRAIGHT_LINE', max_length=20)),
                ('salvage_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='organization.church')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_categories', to='assets.assetcategorytemplate')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('church', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_straight_line', models.BooleanField(default=True)),
                ('allow_declining_balance', models.BooleanField(default=True)),
                ('default_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line'), ('DECLINING_BALANCE', 'Declining balance (150% DB)')], default='STRAIGHT_LINE', max_length=20)),
                ('auto_run_monthly', models.BooleanField(default=False, help_text='Automatically post depreciation on the run day each month.')),
                ('run_day_of_month', models.PositiveSmallIntegerField(default=28, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('post_depreciation_to_ledger', models.BooleanField(default=True)),
                ('capitalize_on_approval', models.BooleanField(default=True, help_text='Post acquisition entry when an asset is approved.')),
                ('default_payment_account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='BANK', max_length=10)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_policy', to='organization.church')),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('gra_asset_class', models.CharField(choices=[('1', 'Class 1 — Buildings & structures'), ('2', 'Class 2 — Vehicles, plant & heavy equipment'), ('3', 'Class 3 — IT, office equipment, fixtures'), ('4', 'Class 4 — Low-value / short-life items')], default='3', max_length=1)),
                ('purchase_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('useful_life_months', models.PositiveIntegerField(default=48)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line'), ('DECLINING_BALANCE', 'Declining balance (150% DB)')], default='STRAIGHT_LINE', max_length=20)),
                ('custodian_name', models.CharField(blank=True, max_length=120)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('invoice_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('UNDER_REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('disposed_at', models.DateField(blank=True, null=True)),
                ('disposal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquisition_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalized_assets', to='transactions.transaction')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='organization.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('custodian_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_assets', to='members.member')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.fixedasset')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method_used', models.CharField(max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciation_entries', to='transactions.transaction')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.fixedasset')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='AssetAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='assets.fixedasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['church', 'status'], name='assets_fixe_church__96c484_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['church', 'asset_code'], name='assets_fixe_church__ca8d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fixedasset',
            unique_together={('church', 'asset_code')},
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciationentry',
            unique_together={('asset', 'period_year', 'period_month')},
        ),
    ]
