# Generated by Django 5.1.15 on 2026-07-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assets_enterprise'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetauditlog',
            new_name='assets_asse_asset_i_4219b0_idx',
            old_name='assets_asse_asset_i_6f2c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='assetpolicyauditlog',
            new_name='assets_asse_church__99701a_idx',
            old_name='assets_asse_church__a8e4b1_idx',
        ),
    ]
