# Generated by Django 6.0.6 on 2026-07-04 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('MATRIX_UPDATE', 'Matrix Update'), ('MATRIX_RESET', 'Matrix Reset'), ('OVERRIDE_CREATE', 'Override Created'), ('OVERRIDE_UPDATE', 'Override Updated'), ('OVERRIDE_DELETE', 'Override Removed')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='permissions_created_539de3_idx'), models.Index(fields=['action'], name='permissions_action_786835_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted', models.BooleanField(help_text='True = grant permission; False = explicitly deny.')),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='permissions.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'permission', 'is_active'], name='permissions_user_id_ac1124_idx'), models.Index(fields=['expires_at'], name='permissions_expires_cade14_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('GENERAL_OVERSEER', 'General Overseer'), ('DISTRICT_PASTOR', 'District Pastor'), ('LOCAL_PASTOR', 'Local Pastor'), ('SECRETARY', 'Secretary'), ('TREASURY', 'Treasury'), ('MEMBER', 'Member')], db_index=True, max_length=30)),
                ('granted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='permissions.permission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'permission__category', 'permission__sort_order'],
                'indexes': [models.Index(fields=['role', 'permission'], name='permissions_role_fa8758_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
