# Generated by Django 5.1.15 on 2026-07-23 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('INFO', 'Info'), ('FINANCE', 'Finance'), ('MEMBER', 'Member'), ('MEETING', 'Meeting'), ('SYSTEM', 'System')], default='INFO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'category', 'read'], name='dashboard_n_user_id_1113c1_idx'),
        ),
    ]
