# Generated by Django 5.1.15

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_enterprise_comms_phase12"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stable key so unread duplicates of the same event are coalesced.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="last_event_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
        migrations.AddField(
            model_name="notification",
            name="occurrence_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="notification",
            name="severity",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("CRITICAL", "Critical"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "-last_event_at"], name="dash_n_user_lstev_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "event_key", "read"], name="dash_n_user_evtrd_idx"),
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-last_event_at", "-created_at"]},
        ),
    ]
