# Generated by Django 5.1.15 on 2026-09-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_notification_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_event_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
