# Generated by Django 6.0.6 on 2026-07-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivitylog_userinvitation_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_2b136f_idx',
            old_name='accounts_us_role_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_church__ec764c_idx',
            old_name='accounts_us_church_4e9b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='accounts_us_user_id_3d3e81_idx',
            old_name='accounts_us_user_id_7c3f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='accounts_us_created_643629_idx',
            old_name='accounts_us_created_2a8e4b_idx',
        ),
    ]
