# Generated by Django 6.0.6 on 2026-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_user',
            field=models.BooleanField(default=False, help_text='Platform operator — access /platform/ only, not the institution dashboard.'),
        ),
    ]
