# Generated by Django 6.0.6 on 2026-07-07 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_platform_control_room'),
        ('members', '0003_leadershiprole_spiritualgift_memberspiritualgift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='members.member'),
        ),
    ]
