# Generated by Django 6.0.6 on 2026-07-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_managed_denominations'),
        ('sitecontrol', '0008_control_tower_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Platform Owner'), ('SECURITY', 'Security Admin'), ('BILLING', 'Billing Admin'), ('SUPPORT', 'Support Operator'), ('READONLY', 'Read Only')], default='', help_text='Meaningful only when is_platform_user=True. Controls platform capabilities.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_denominations',
            field=models.ManyToManyField(blank=True, help_text='Platform operators: denominations this operator may manage. Empty no longer means global — only Owner / break-glass superusers have global access.', related_name='platform_operators', to='sitecontrol.denomination'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('GENERAL_OVERSEER', 'General Overseer'), ('DISTRICT_PASTOR', 'District Pastor'), ('LOCAL_PASTOR', 'Local Pastor'), ('SECRETARY', 'Secretary'), ('TREASURY', 'Treasury'), ('BOARD_MEMBER', 'Board Member'), ('MEMBER', 'Member')], default='MEMBER', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('GENERAL_OVERSEER', 'General Overseer'), ('DISTRICT_PASTOR', 'District Pastor'), ('LOCAL_PASTOR', 'Local Pastor'), ('SECRETARY', 'Secretary'), ('TREASURY', 'Treasury'), ('BOARD_MEMBER', 'Board Member'), ('MEMBER', 'Member')], max_length=30),
        ),
    ]
