# Generated by Django 6.0.6 on 2026-07-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_assign_platform_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='MFA readiness stub — enforcement not yet implemented.'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('CHURCH_ASSIGN', 'Church Assignment'), ('USER_CREATE', 'User Created'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_ACTIVATE', 'User Activated'), ('INVITE_SENT', 'Invitation Sent'), ('INVITE_ACCEPTED', 'Invitation Accepted'), ('INVITE_REVOKED', 'Invitation Revoked'), ('INVITE_RESENT', 'Invitation Resent'), ('PROFILE_UPDATE', 'Profile Updated'), ('EMAIL_CHANGE', 'Email Changed')], max_length=30),
        ),
    ]
