# Generated by Django 6.0.6 on 2026-07-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_org_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_scope_l_3a0190_idx',
            old_name='accounts_us_scope_l_7c2e1a_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_recovery_hashes',
            field=models.JSONField(blank=True, default=list, help_text='SHA-256 hashes of unused MFA recovery codes.'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.TextField(blank=True, default='', help_text='Encrypted TOTP shared secret (empty when MFA is not enrolled).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='When True, TOTP MFA is enrolled and enforced at login for privileged roles.'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('CHURCH_ASSIGN', 'Church Assignment'), ('USER_CREATE', 'User Created'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_ACTIVATE', 'User Activated'), ('INVITE_SENT', 'Invitation Sent'), ('INVITE_ACCEPTED', 'Invitation Accepted'), ('INVITE_REVOKED', 'Invitation Revoked'), ('INVITE_RESENT', 'Invitation Resent'), ('PROFILE_UPDATE', 'Profile Updated'), ('EMAIL_CHANGE', 'Email Changed'), ('SCOPE_CHANGE', 'Organization Scope Changed'), ('MFA_ENROLL', 'MFA Enrolled'), ('MFA_VERIFY', 'MFA Verified'), ('MFA_RECOVERY', 'MFA Recovery Code Used')], max_length=30),
        ),
    ]
