# Generated by Django 5.1.15 on 2026-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mfa_trusted_device_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='accounts_tr_user_id_9458da_idx',
            old_name='accounts_tr_user_id_7b8e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='accounts_tr_token_h_5a82bb_idx',
            old_name='accounts_tr_token_h_1c2d3e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='When True, MFA is enrolled for this user (enforced only if site policy requires it).'),
        ),
    ]
