# Generated by Django 5.1.15 on 2026-07-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_accounts_tr_user_id_7b8e0a_idx_accounts_tr_user_id_9458da_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_receipt_auto_approve',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-user override: receipts up to this amount auto-approve. Blank = use church treasury policy. 0 = always need second approval.', max_digits=14, null=True),
        ),
    ]
