# Generated by Django 5.1.15 on 2026-07-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_treasury_receipt_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='When True, member portal users must set a new password after sign-in.'),
        ),
    ]
