# Generated by Django 5.1.15 on 2026-08-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('CHURCH_ASSIGN', 'Church Assignment'), ('USER_CREATE', 'User Created'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_ACTIVATE', 'User Activated'), ('INVITE_SENT', 'Invitation Sent'), ('INVITE_ACCEPTED', 'Invitation Accepted'), ('INVITE_REVOKED', 'Invitation Revoked'), ('INVITE_RESENT', 'Invitation Resent'), ('PROFILE_UPDATE', 'Profile Updated'), ('EMAIL_CHANGE', 'Email Changed'), ('SCOPE_CHANGE', 'Organization Scope Changed'), ('MFA_ENROLL', 'MFA Enrolled'), ('MFA_VERIFY', 'MFA Verified'), ('MFA_RECOVERY', 'MFA Recovery Code Used'), ('MFA_EMAIL', 'MFA Email Code Used'), ('MFA_TRUSTED_DEVICE', 'MFA Trusted Device Login'), ('INSTITUTION_BRANDING_UPDATE', 'Institution Branding Updated')], max_length=30),
        ),
    ]
