# Generated by Django 5.1.15 on 2026-09-17 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_system_settings_activity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0, help_text='Incremented to invalidate other browser sessions (password change / logout-all).'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_CHANGE', 'Role Change'), ('CHURCH_ASSIGN', 'Church Assignment'), ('USER_CREATE', 'User Created'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_ACTIVATE', 'User Activated'), ('INVITE_SENT', 'Invitation Sent'), ('INVITE_ACCEPTED', 'Invitation Accepted'), ('INVITE_REVOKED', 'Invitation Revoked'), ('INVITE_RESENT', 'Invitation Resent'), ('PROFILE_UPDATE', 'Profile Updated'), ('EMAIL_CHANGE', 'Email Changed'), ('SCOPE_CHANGE', 'Organization Scope Changed'), ('MFA_ENROLL', 'MFA Enrolled'), ('MFA_VERIFY', 'MFA Verified'), ('MFA_RECOVERY', 'MFA Recovery Code Used'), ('MFA_EMAIL', 'MFA Email Code Used'), ('MFA_TRUSTED_DEVICE', 'MFA Trusted Device Login'), ('INSTITUTION_BRANDING_UPDATE', 'Institution Branding Updated'), ('SYSTEM_SETTINGS_UPDATE', 'System Settings Updated'), ('SESSION_REVOKE', 'Other Sessions Revoked')], max_length=30),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_0f22a1_idx')],
            },
        ),
    ]
