# Generated by Django 6.0.6 on 2026-07-09 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('members', '0003_leadershiprole_spiritualgift_memberspiritualgift'),
        ('organization', '0003_conference_denomination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chair_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('BOARD', 'Board Meeting'), ('CHURCH_BOARD', 'Church Board'), ('DEACONS', 'Deacons Council'), ('DEPARTMENT', 'Department Meeting'), ('GENERAL', 'General Meeting'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_adjournment',
            field=models.TextField(blank=True, help_text='Closing and adjournment.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_minutes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_deliberations',
            field=models.TextField(blank=True, help_text='Discussion and reports.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_motions',
            field=models.TextField(blank=True, help_text='Motions raised.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_opening',
            field=models.TextField(blank=True, help_text='Call to order, opening prayer, quorum.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_previous',
            field=models.TextField(blank=True, help_text='Approval of previous minutes.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_minutes_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_votes',
            field=models.TextField(blank=True, help_text='Votes and outcomes.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='meetingattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingdecision',
            name='motion_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meetingdecision',
            name='vote_result',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, help_text='Supplementary notes.'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['church', 'scheduled_at'], name='meetings_me_church__2c6322_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['church', 'minutes_status'], name='meetings_me_church__b3b105_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['church', 'meeting_type'], name='meetings_me_church__895c58_idx'),
        ),
    ]
