# Generated by Django 5.1.15 on 2026-07-24 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_workflow'),
        ('members', '0008_member_portal_email_unique_and_dob'),
        ('organization', '0005_backfill_financials_provisioned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='join_passcode',
            field=models.CharField(blank=True, help_text='Optional meeting passcode shown to authorized members.', max_length=64),
        ),
        migrations.AddField(
            model_name='meeting',
            name='join_url',
            field=models.URLField(blank=True, help_text='Zoom (or other) join link for online / live sessions.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='show_on_portal',
            field=models.BooleanField(default=False, help_text='When enabled, scheduled meetings with a join link appear on the member portal.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('BOARD', 'Board Meeting'), ('CHURCH_BOARD', 'Church Board'), ('DEACONS', 'Deacons Council'), ('DEPARTMENT', 'Department Meeting'), ('GENERAL', 'General Meeting'), ('ONLINE_SERVICE', 'Online / Live Service'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['church', 'show_on_portal', 'scheduled_at'], name='meetings_me_church__965ae5_idx'),
        ),
    ]
