# Generated by Django 4.2.30 on 2026-07-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('TITHE', 'Tithe'), ('COMBINED', 'Combined Offering'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('DISTRICT_PAYABLE', 'District Payable'), ('BANK', 'Bank'), ('CASH', 'Cash')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organization.church')),
            ],
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(limit_choices_to={'account_type': 'BANK'}, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='transactions.account')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='organization.church')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organization.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lines', to='transactions.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('remit_to_district', models.BooleanField(default=False, help_text='If true, amounts are included in district remittance.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offering_categories', to='transactions.account')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_categories', to='organization.church')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCutoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Use first day of month (e.g. 2026-02-01)')),
                ('total_tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_combined', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_cutoffs', to='organization.church')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VOID', 'Void'), ('REMIT', 'District Remittance')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_audit_logs', to='organization.church')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('CHURCH', 'Church'), ('DISTRICT', 'District'), ('CONFERENCE', 'Conference')], default='CHURCH', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='transactions.account')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organization.church')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organization.conference')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organization.district')),
            ],
            options={
                'ordering': ['-year', 'account__name'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_reference', models.CharField(blank=True, max_length=100)),
                ('is_matched', models.BooleanField(default=False)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.bankreconciliation')),
                ('transaction_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_items', to='transactions.transactionline')),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['church', 'approval_status', 'date'], name='transaction_church__100273_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['church', 'transaction_type'], name='transaction_church__841333_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='transaction_referen_923a88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offeringcategory',
            unique_together={('church', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlycutoff',
            unique_together={('church', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('church', 'name')},
        ),
    ]
