# Generated by Django 6.0.6 on 2026-07-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_ledger_category'),
        ('transactions', '0003_transaction_is_voided_transaction_reversal_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ledger_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledger.ledgercategory'),
        ),
    ]
