# Generated by Django 6.0.6 on 2026-07-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_fix_welfare_fund_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('TITHE', 'Tithe'), ('COMBINED', 'Combined Offering'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('DISTRICT_PAYABLE', 'District Payable'), ('TITHE_REMIT_PAYABLE', 'Tithe Remittance Payable'), ('COMBINED_REMIT_PAYABLE', 'Combined Remittance Payable'), ('COMBINED_RETENTION', 'Combined Retention Income'), ('WELFARE_FUND', 'Welfare Fund'), ('REMITTANCE_RECEIVABLE', 'Remittance Receivable'), ('SALARY_EXPENSE', 'Salary Expense'), ('EMPLOYER_SSNIT_EXPENSE', 'Employer SSNIT Expense'), ('SALARIES_PAYABLE', 'Salaries Payable'), ('PAYE_PAYABLE', 'PAYE Payable'), ('SSNIT_PAYABLE', 'SSNIT Payable'), ('PENSION_PAYABLE', 'Pension Payable'), ('BANK', 'Bank'), ('CASH', 'Cash')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('PAYROLL', 'Payroll')], max_length=20),
        ),
    ]
