# Generated by Django 6.0.6 on 2026-07-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_workingday'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workingday',
            new_name='transaction_church__96e795_idx',
            old_name='transaction_church__a8f4c2_idx',
        ),
        migrations.RenameIndex(
            model_name='workingday',
            new_name='transaction_church__a5d15d_idx',
            old_name='transaction_church__b1e9d3_idx',
        ),
    ]
