# Generated by Django 6.0.6 on 2026-07-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("transactions", "0011_welfare_enterprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="members.department",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="level",
            field=models.CharField(
                choices=[
                    ("CHURCH", "Church"),
                    ("DEPARTMENT", "Department"),
                    ("DISTRICT", "District"),
                    ("CONFERENCE", "Conference"),
                ],
                default="CHURCH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("APPROVE", "Approve"),
                    ("REJECT", "Reject"),
                    ("VOID", "Void"),
                    ("REMIT", "District Remittance"),
                    ("BUDGET_CREATE", "Budget Create"),
                    ("BUDGET_UPDATE", "Budget Update"),
                    ("BUDGET_DELETE", "Budget Delete"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("department__isnull", True), ("level", "CHURCH")),
                fields=("church", "year", "account"),
                name="uniq_budget_church_account_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("level", "DEPARTMENT")),
                fields=("church", "year", "account", "department"),
                name="uniq_budget_department_account_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("level", "DISTRICT")),
                fields=("district", "year", "account"),
                name="uniq_budget_district_account_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("level", "CONFERENCE")),
                fields=("conference", "year", "account"),
                name="uniq_budget_conference_account_year",
            ),
        ),
    ]
