# Generated by Django 6.0.6 on 2026-07-17 07:08

from django.db import migrations, models


def backfill_account_codes(apps, schema_editor):
    Account = apps.get_model("transactions", "Account")
    # Inline map to avoid importing app code during migration
    code_by_name = {
        "Tithe": "TITHE",
        "Combined Offering": "COMBINED",
        "General Income": "INCOME",
        "General Expense": "EXPENSE",
        "District Payable": "DISTRICT_PAYABLE",
        "Tithe Remittance Payable": "TITHE_REMIT_PAYABLE",
        "Combined Remittance Payable": "COMBINED_REMIT_PAYABLE",
        "Combined Retention Income": "COMBINED_RETENTION",
        "Welfare Fund": "WELFARE_FUND",
        "Remittance Receivable": "REMITTANCE_RECEIVABLE",
        "Salaries & Allowances": "SALARY_EXPENSE",
        "Employer SSNIT Expense": "EMPLOYER_SSNIT_EXPENSE",
        "Salaries Payable": "SALARIES_PAYABLE",
        "PAYE Payable": "PAYE_PAYABLE",
        "SSNIT Payable": "SSNIT_PAYABLE",
        "Pension Payable": "PENSION_PAYABLE",
        "Main Bank": "BANK",
        "Cash": "CASH",
        "Property, Plant & Equipment": "FIXED_ASSET",
        "Accumulated Depreciation": "ACCUM_DEPR",
        "Depreciation Expense": "DEPR_EXPENSE",
        "District Tithe Remittance": "DISTRICT_TITHE_REMIT",
        "Conference Tithe Remittance": "CONF_TITHE_REMIT",
        "Union Tithe Remittance": "UNION_TITHE_REMIT",
        "District Combined Remittance": "DISTRICT_COMBINED_REMIT",
        "Conference Combined Remittance": "CONF_COMBINED_REMIT",
        "Union Combined Remittance": "UNION_COMBINED_REMIT",
        "Petty Cash": "PETTY_CASH",
        "Utilities Expense": "UTILITIES",
        "Rent Expense": "RENT",
        "Maintenance & Repairs": "MAINTENANCE",
        "Transport & Travel": "TRANSPORT",
        "Office Supplies": "SUPPLIES",
        "Missions & Outreach": "MISSIONS",
        "Welfare Assistance": "WELFARE_ASSIST",
        "Bank Charges": "BANK_CHARGES",
        "Thanksgiving Offering": "THANKSGIVING",
        "Building Fund": "BUILDING",
        "Mission Offering": "MISSION_OFFERING",
        "Special Project Income": "SPECIAL_PROJECT",
        "Accrued Expenses": "ACCRUED_EXPENSE",
    }
    used = {}
    for account in Account.objects.all().iterator():
        church_id = str(account.church_id)
        used.setdefault(church_id, set())
        code = code_by_name.get(account.name, "")
        if not code:
            base = "".join(ch if ch.isalnum() else "_" for ch in account.name.upper())[:32].strip("_")
            code = base or f"ACCT_{str(account.pk).replace('-', '')[:8].upper()}"
        original = code
        n = 1
        while code in used[church_id]:
            n += 1
            code = f"{original[:34]}_{n}"
        used[church_id].add(code)
        if account.code != code:
            account.code = code
            account.save(update_fields=["code"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_backfill_financials_provisioned"),
        ("transactions", "0016_payroll_idempotency_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stable account code for lookups (unique per church when set).",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_account_codes, noop_reverse),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["church", "code"], name="transaction_church__956816_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["church", "is_active"], name="transaction_church__daba51_idx"),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("church", "code"),
                name="account_church_code_uniq",
            ),
        ),
    ]
