# Generated by Django 5.1.15 on 2026-07-21 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledger_enterprise'),
        ('members', '0004_members_enterprise'),
        ('organization', '0005_backfill_financials_provisioned'),
        ('transactions', '0017_account_code_and_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['church', 'account_type'], name='transaction_church__41c5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['church', 'approval_status', 'is_voided', 'date'], name='transaction_church__f98792_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['church', 'member'], name='transaction_church__002364_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['church', 'ledger_category', '-date'], name='transaction_church__603f22_idx'),
        ),
    ]
