# Generated by Django 5.1.15 on 2026-07-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='transactions.transaction'),
        ),
    ]
