# Generated by Django 5.1.15 on 2026-07-23 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_backfill_financials_provisioned'),
        ('transactions', '0019_financial_audit_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_auto_approve_enabled', models.BooleanField(default=True, help_text='When enabled, income/receipts within the limit are auto-approved.')),
                ('default_receipt_auto_approve_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Church default: receipts up to this amount auto-approve. Leave blank for unlimited (all receipts auto-approve). Set 0 to require second approval for every receipt.', max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_approval_policy', to='organization.church')),
            ],
            options={
                'verbose_name': 'Treasury approval policy',
                'verbose_name_plural': 'Treasury approval policies',
            },
        ),
    ]
