# Generated by Django 5.1.15 on 2026-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_phase3_contribution_and_reversal_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10),
        ),
    ]
