# Generated by Django 6.0.6 on 2026-07-07 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_key', models.SlugField(max_length=60)),
                ('export_format', models.CharField(max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('export_file', models.FileField(blank=True, upload_to='exports/reports/')),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='reports_rep_user_id_39bbd1_idx')],
            },
        ),
    ]
