# Generated by Django 5.1.15 on 2026-09-09 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_church_history_entry'),
        ('sitecontrol', '0025_activation_request_requested_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('finance', 'Finance'), ('members', 'Members'), ('payroll', 'Payroll'), ('organization', 'Organization'), ('permissions', 'Permissions'), ('platform', 'Platform'), ('other', 'Other')], db_index=True, max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('error', 'Error')], default='success', max_length=16)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=200)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_audit_events', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_audit_events', to='organization.church')),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_audit_events', to='sitecontrol.denomination')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['church', 'occurred_at'], name='audit_evt_church_dt_idx'), models.Index(fields=['domain', 'action', 'occurred_at'], name='audit_evt_dom_act_dt_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_evt_object_idx')],
            },
        ),
    ]
