from django.urls import path

from . import views
from . import views_registration
from . import views_denominations
from . import views_import

app_name = "sitecontrol"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("setup/", views.setup_checklist, name="setup"),
    path("health/", views.health, name="health"),
    path("ops/", views.ops_health, name="ops_health"),
    path("audit/", views.audit_log, name="audit_log"),
    path("audit/export/", views.audit_export, name="audit_export"),
    path("settings/", views.site_settings, name="settings"),
    path("settings/branding/", views.branding_settings, name="branding"),
    path("settings/email/", views.email_settings, name="email_settings"),
    path("settings/security/", views.security_settings, name="security_settings"),
    path("settings/features/", views.feature_registry, name="features"),
    path("settings/member-lookups/", views.member_lookup_list, name="member_lookup_list"),
    path("settings/member-lookups/add/", views.member_lookup_edit, name="member_lookup_add"),
    path("settings/member-lookups/<uuid:pk>/edit/", views.member_lookup_edit, name="member_lookup_edit"),
    path("registration/", views_registration.registration_settings, name="registration_settings"),
    path("applications/", views_registration.application_list, name="application_list"),
    path("applications/<uuid:pk>/", views_registration.application_detail, name="application_detail"),
    path("applications/<uuid:pk>/approve/", views_registration.application_approve, name="application_approve"),
    path("applications/<uuid:pk>/reject/", views_registration.application_reject, name="application_reject"),
    path("plans/", views.plan_list, name="plan_list"),
    path("plans/add/", views.plan_edit, name="plan_add"),
    path("plans/<uuid:pk>/edit/", views.plan_edit, name="plan_edit"),
    path("billing/", views.billing_settings, name="billing_settings"),
    path("payment-methods/", views.payment_method_list, name="payment_method_list"),
    path("payment-methods/add/", views.payment_method_edit, name="payment_method_add"),
    path("payment-methods/<uuid:pk>/edit/", views.payment_method_edit, name="payment_method_edit"),
    path("subscriptions/", views.subscription_list, name="subscription_list"),
    path("subscriptions/add/", views.subscription_edit, name="subscription_add"),
    path("subscriptions/<uuid:pk>/edit/", views.subscription_edit, name="subscription_edit"),
    path("subscriptions/<uuid:pk>/record-payment/", views.subscription_record_payment, name="subscription_record_payment"),
    path("subscriptions/seed-defaults/", views.subscription_bulk_seed, name="subscription_seed"),
    path("denominations/", views_denominations.denomination_list, name="denomination_list"),
    path("denominations/billing/", views_denominations.denomination_billing_rollups, name="denomination_billing_rollups"),
    path("denominations/add/", views_denominations.denomination_edit, name="denomination_add"),
    path("denominations/seed-builtin/", views_denominations.denomination_seed_builtins, name="denomination_seed"),
    path("denominations/<uuid:pk>/", views_denominations.denomination_detail, name="denomination_detail"),
    path("denominations/<uuid:pk>/edit/", views_denominations.denomination_edit, name="denomination_edit"),
    path("denominations/<uuid:pk>/terminology/", views_denominations.denomination_terminology, name="denomination_terminology"),
    path("denominations/<uuid:pk>/seeds/", views_denominations.denomination_seeds, name="denomination_seeds"),
    path("denominations/<uuid:pk>/branding/", views_denominations.denomination_branding, name="denomination_branding"),
    path("denominations/<uuid:pk>/billing/", views_denominations.denomination_billing, name="denomination_billing"),
    path("denominations/<uuid:pk>/set-context/", views_denominations.denomination_set_context, name="denomination_set_context"),
    path("denominations/clear-context/", views_denominations.denomination_clear_context, name="clear_denomination_context"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/provision/", views.tenant_provision, name="tenant_provision"),
    path("tenants/<uuid:pk>/", views.tenant_detail, name="tenant_detail"),
    path("tenants/<uuid:pk>/users/<uuid:user_id>/role/", views.tenant_set_user_role, name="tenant_set_user_role"),
    path("tenants/<uuid:pk>/edit/", views.tenant_edit, name="tenant_edit"),
    path("tenants/<uuid:pk>/reprovision-financials/", views.tenant_reprovision_financials, name="tenant_reprovision_financials"),
    path("tenants/<uuid:pk>/suspend/", views.tenant_suspend, name="tenant_suspend"),
    path("tenants/<uuid:pk>/reactivate/", views.tenant_reactivate, name="tenant_reactivate"),
    path("tenants/<uuid:pk>/offboard/", views.tenant_offboard, name="tenant_offboard"),
    path(
        "tenants/<uuid:pk>/invitations/<uuid:invite_pk>/resend/",
        views.tenant_resend_invitation,
        name="tenant_resend_invitation",
    ),
    path(
        "tenants/<uuid:pk>/invitations/create/",
        views.tenant_create_admin_invitation,
        name="tenant_create_admin_invitation",
    ),
    path("impersonate/<uuid:user_id>/", views.impersonate_start, name="impersonate_start"),
    path("impersonate/end/", views.impersonate_end, name="impersonate_end"),
    path("organization/", views.hierarchy, name="hierarchy"),
    path("operators/", views.operator_list, name="operator_list"),
    path("operators/add/", views.operator_create, name="operator_add"),
    path("operators/<uuid:pk>/edit/", views.operator_edit, name="operator_edit"),
    path("operators/<uuid:pk>/deactivate/", views.operator_deactivate, name="operator_deactivate"),
    path("announcements/", views.announcement_list, name="announcement_list"),
    path("announcements/add/", views.announcement_edit, name="announcement_add"),
    path("announcements/<uuid:pk>/edit/", views.announcement_edit, name="announcement_edit"),
    path("import/", views_import.import_hub, name="import_hub"),
    path("import/members/", views_import.import_members, name="import_members"),
    path("import/members/template/", views_import.import_member_template, name="import_member_template"),
    path("import/transactions/", views_import.import_transactions, name="import_transactions"),
    path(
        "import/transactions/template/",
        views_import.import_transaction_template,
        name="import_transaction_template",
    ),
]
