# Generated by Django 6.0.6 on 2026-07-04 23:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_generalconference_union_conference_union'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='ChurchHub', max_length=120)),
                ('site_tagline', models.CharField(blank=True, default='Enterprise Church Management', max_length=200)),
                ('support_email', models.EmailField(blank=True, default='support@churchhub.local', max_length=254)),
                ('admin_primary_color', models.CharField(default='#1e3a5f', max_length=7)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=240, help_text='Idle session length before re-login is required.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('login_max_attempts', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('login_lockout_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, only superusers may sign in.')),
                ('maintenance_message', models.CharField(blank=True, default='The system is undergoing scheduled maintenance. Please try again later.', max_length=300)),
                ('allow_church_self_registration', models.BooleanField(default=False)),
                ('enforce_subscription_limits', models.BooleanField(default=False, help_text='Apply plan user/branch limits and feature flags.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Max active users per church.')),
                ('max_branches', models.PositiveIntegerField(default=1, help_text='Max churches/branches under one district subscription anchor.')),
                ('feature_payroll', models.BooleanField(default=False)),
                ('feature_remittance', models.BooleanField(default=True)),
                ('feature_ledger', models.BooleanField(default=True)),
                ('feature_meetings', models.BooleanField(default=True)),
                ('feature_advanced_reports', models.BooleanField(default=False)),
                ('feature_budgets', models.BooleanField(default=True)),
                ('feature_giving_portal', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=12)),
                ('started_at', models.DateField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('override_max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('override_max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organization.church')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='sitecontrol.subscriptionplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
