# Generated by Django 6.0.6 on 2026-07-07 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_platform_control_room'),
        ('organization', '0002_generalconference_union_conference_union'),
        ('sitecontrol', '0002_platform_control_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_institution_church_onboarding',
            field=models.BooleanField(default=True, help_text='Allow hierarchy admins to onboard churches from the institution app.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_institution_user_invites',
            field=models.BooleanField(default=True, help_text='Allow church admins to invite institution users.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='application_default_plan',
            field=models.ForeignKey(blank=True, help_text='Plan assigned when an application is approved (default plan if empty).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sitecontrol.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='application_default_role',
            field=models.CharField(default='LOCAL_PASTOR', help_text='Role for the first user invited when an application is approved.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_intro',
            field=models.TextField(blank=True, default='Apply to register your church on ChurchHub. A platform administrator will review your request.'),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SETTINGS_UPDATE', 'Settings Updated'), ('PLAN_UPDATE', 'Plan Updated'), ('SUBSCRIPTION_UPDATE', 'Subscription Updated'), ('TENANT_UPDATE', 'Tenant Updated'), ('OPERATOR_CREATE', 'Platform Operator Created'), ('OPERATOR_UPDATE', 'Platform Operator Updated'), ('OPERATOR_DEACTIVATE', 'Platform Operator Deactivated'), ('ANNOUNCEMENT_UPDATE', 'Announcement Updated'), ('FEATURE_UPDATE', 'Feature Registry Updated'), ('MAINTENANCE_TOGGLE', 'Maintenance Mode Toggled'), ('REGISTRATION_UPDATE', 'Registration Settings Updated'), ('APPLICATION_SUBMIT', 'Tenant Application Submitted'), ('APPLICATION_APPROVE', 'Tenant Application Approved'), ('APPLICATION_REJECT', 'Tenant Application Rejected')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='allow_church_self_registration',
            field=models.BooleanField(default=False, help_text='Allow public church registration applications at /apply/.'),
        ),
        migrations.CreateModel(
            name='TenantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=12)),
                ('application_type', models.CharField(choices=[('EXISTING_DISTRICT', 'Existing district'), ('NEW_HIERARCHY', 'New organization path')], default='EXISTING_DISTRICT', max_length=20)),
                ('church_name', models.CharField(max_length=200)),
                ('church_code', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('conference_name', models.CharField(blank=True, max_length=200)),
                ('conference_code', models.CharField(blank=True, max_length=20)),
                ('zone_name', models.CharField(blank=True, max_length=200)),
                ('zone_code', models.CharField(blank=True, max_length=20)),
                ('district_name', models.CharField(blank=True, max_length=200)),
                ('district_code', models.CharField(blank=True, max_length=20)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('applicant_username', models.CharField(max_length=150)),
                ('applicant_notes', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_application', to='organization.church')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_applications', to='organization.district')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_application', to='accounts.userinvitation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sitecontrol_status_ec1228_idx'), models.Index(fields=['contact_email'], name='sitecontrol_contact_d6fd7d_idx')],
            },
        ),
    ]
