# Generated by Django 6.0.6 on 2026-07-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0003_tenant_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='global_enable_assets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_assets',
            field=models.BooleanField(default=True),
        ),
    ]
