# Generated by Django 6.0.6 on 2026-07-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0006_denomination_phases'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='denomination',
            new_name='sitecontrol_is_acti_b44c69_idx',
            old_name='sitecontrol_is_acti_0a8f2a_idx',
        ),
    ]
