# Generated by Django 6.0.6 on 2026-07-10 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0007_rename_sitecontrol_is_acti_0a8f2a_idx_sitecontrol_is_acti_b44c69_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_block_apply',
            field=models.BooleanField(default=True, help_text='When maintenance mode is on, also block public /apply/ registration.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_ip_allowlist',
            field=models.TextField(blank=True, default='', help_text='Newline-separated IPs allowed for platform access. Empty = allow all.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Optional encrypted SMTP password storage (Phase 2).'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='feature_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-feature overrides of the plan, e.g. {"payroll": true}.'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='lifecycle_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_suspended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SETTINGS_UPDATE', 'Settings Updated'), ('PLAN_UPDATE', 'Plan Updated'), ('SUBSCRIPTION_UPDATE', 'Subscription Updated'), ('TENANT_UPDATE', 'Tenant Updated'), ('TENANT_SUSPEND', 'Tenant Suspended'), ('TENANT_REACTIVATE', 'Tenant Reactivated'), ('TENANT_OFFBOARD', 'Tenant Offboarded'), ('OPERATOR_CREATE', 'Platform Operator Created'), ('OPERATOR_UPDATE', 'Platform Operator Updated'), ('OPERATOR_DEACTIVATE', 'Platform Operator Deactivated'), ('ANNOUNCEMENT_UPDATE', 'Announcement Updated'), ('FEATURE_UPDATE', 'Feature Registry Updated'), ('MAINTENANCE_TOGGLE', 'Maintenance Mode Toggled'), ('REGISTRATION_UPDATE', 'Registration Settings Updated'), ('APPLICATION_SUBMIT', 'Tenant Application Submitted'), ('APPLICATION_APPROVE', 'Tenant Application Approved'), ('APPLICATION_REJECT', 'Tenant Application Rejected'), ('DENOMINATION_CREATE', 'Denomination Created'), ('DENOMINATION_UPDATE', 'Denomination Updated'), ('DENOMINATION_SEED', 'Denomination Profiles Seeded'), ('DENOMINATION_TERMINOLOGY', 'Denomination Terminology Updated'), ('DENOMINATION_SEEDS_CONFIG', 'Denomination Seed Config Updated'), ('DENOMINATION_BILLING_VIEW', 'Denomination Billing Viewed'), ('AUDIT_EXPORT', 'Audit Log Exported'), ('OPS_EMAIL_TEST', 'Ops Email Test Sent'), ('IMPERSONATE_START', 'Impersonation Started'), ('IMPERSONATE_END', 'Impersonation Ended'), ('BREAKGLASS_GRANT', 'Break-glass Access Granted')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enforce_subscription_limits',
            field=models.BooleanField(default=True, help_text='Apply plan user/branch limits and feature flags.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Plaintext SMTP password (legacy). Prefer smtp_password_encrypted when available.', max_length=200),
        ),
    ]
