# Generated by Django 6.0.6 on 2026-07-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0010_login_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mfa_required_for_privileged',
            field=models.BooleanField(default=True, help_text='Require TOTP MFA for platform OWNER/SECURITY, institution SUPER_ADMIN, TREASURY, and Django superusers.'),
        ),
    ]
