# Generated by Django 5.1.15 on 2026-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0012_mfa_audience_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#1d4ed8', help_text='Action color for primary buttons and links.', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_primary_color',
            field=models.CharField(default='#1e3a5f', help_text='Brand/chrome color (navbar, table headers). Navy recommended.', max_length=7),
        ),
    ]
