# Generated by Django 5.1.15 on 2026-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0013_alter_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SETTINGS_UPDATE', 'Settings Updated'), ('PLAN_UPDATE', 'Plan Updated'), ('SUBSCRIPTION_UPDATE', 'Subscription Updated'), ('SUBSCRIPTION_PAYMENT', 'Subscription Payment Recorded'), ('TENANT_UPDATE', 'Tenant Updated'), ('TENANT_SUSPEND', 'Tenant Suspended'), ('TENANT_REACTIVATE', 'Tenant Reactivated'), ('TENANT_OFFBOARD', 'Tenant Offboarded'), ('OPERATOR_CREATE', 'Platform Operator Created'), ('OPERATOR_UPDATE', 'Platform Operator Updated'), ('OPERATOR_DEACTIVATE', 'Platform Operator Deactivated'), ('ANNOUNCEMENT_UPDATE', 'Announcement Updated'), ('FEATURE_UPDATE', 'Feature Registry Updated'), ('MAINTENANCE_TOGGLE', 'Maintenance Mode Toggled'), ('REGISTRATION_UPDATE', 'Registration Settings Updated'), ('APPLICATION_SUBMIT', 'Tenant Application Submitted'), ('APPLICATION_APPROVE', 'Tenant Application Approved'), ('APPLICATION_REJECT', 'Tenant Application Rejected'), ('TENANT_PROVISION', 'Tenant Provisioned'), ('TENANT_REPROVISION', 'Tenant Financials Re-provisioned'), ('PAYMENT_METHOD_UPDATE', 'Payment Method Updated'), ('SUBSCRIPTIONS_EXPIRED', 'Subscriptions Expired (batch)'), ('DENOMINATION_CREATE', 'Denomination Created'), ('DENOMINATION_UPDATE', 'Denomination Updated'), ('DENOMINATION_SEED', 'Denomination Profiles Seeded'), ('DENOMINATION_TERMINOLOGY', 'Denomination Terminology Updated'), ('DENOMINATION_SEEDS_CONFIG', 'Denomination Seed Config Updated'), ('DENOMINATION_BILLING_VIEW', 'Denomination Billing Viewed'), ('AUDIT_EXPORT', 'Audit Log Exported'), ('OPS_EMAIL_TEST', 'Ops Email Test Sent'), ('IMPERSONATE_START', 'Impersonation Started'), ('IMPERSONATE_END', 'Impersonation Ended'), ('BREAKGLASS_GRANT', 'Break-glass Access Granted')], max_length=40),
        ),
    ]
