# Generated by Django 5.1.15 on 2026-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0014_alter_platformauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='highlight_color',
            field=models.CharField(default='#0e7490', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='highlight_color',
            field=models.CharField(default='#0e7490', help_text='Secondary accent (KPI highlights, portal accents).', max_length=7),
        ),
    ]
