# Generated by Django 5.1.15 on 2026-07-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0016_platform_data_import_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='feature_contribution_campaigns',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_enable_contributions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_contribution_campaigns',
            field=models.BooleanField(default=True),
        ),
    ]
