# Generated by Django 5.1.15 on 2026-08-08 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0018_security_mfa_default_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('public_inquiry_enabled', models.BooleanField(default=False, help_text='Enable only after sales email, consent, and privacy settings are reviewed.')),
                ('sales_notification_email', models.EmailField(blank=True, max_length=254)),
                ('marketing_site_url', models.URLField(blank=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('consent_text', models.TextField(default='I agree that ChurchHub may use these details to respond to my inquiry. I can request deletion by contacting the platform.')),
                ('notify_on_new_lead', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'marketing settings',
            },
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SETTINGS_UPDATE', 'Settings Updated'), ('PLAN_UPDATE', 'Plan Updated'), ('SUBSCRIPTION_UPDATE', 'Subscription Updated'), ('SUBSCRIPTION_PAYMENT', 'Subscription Payment Recorded'), ('TENANT_UPDATE', 'Tenant Updated'), ('TENANT_SUSPEND', 'Tenant Suspended'), ('TENANT_REACTIVATE', 'Tenant Reactivated'), ('TENANT_OFFBOARD', 'Tenant Offboarded'), ('OPERATOR_CREATE', 'Platform Operator Created'), ('OPERATOR_UPDATE', 'Platform Operator Updated'), ('OPERATOR_DEACTIVATE', 'Platform Operator Deactivated'), ('ANNOUNCEMENT_UPDATE', 'Announcement Updated'), ('FEATURE_UPDATE', 'Feature Registry Updated'), ('MAINTENANCE_TOGGLE', 'Maintenance Mode Toggled'), ('REGISTRATION_UPDATE', 'Registration Settings Updated'), ('APPLICATION_SUBMIT', 'Tenant Application Submitted'), ('APPLICATION_APPROVE', 'Tenant Application Approved'), ('APPLICATION_REJECT', 'Tenant Application Rejected'), ('TENANT_PROVISION', 'Tenant Provisioned'), ('TENANT_REPROVISION', 'Tenant Financials Re-provisioned'), ('PAYMENT_METHOD_UPDATE', 'Payment Method Updated'), ('SUBSCRIPTIONS_EXPIRED', 'Subscriptions Expired (batch)'), ('DENOMINATION_CREATE', 'Denomination Created'), ('DENOMINATION_UPDATE', 'Denomination Updated'), ('DENOMINATION_SEED', 'Denomination Profiles Seeded'), ('DENOMINATION_TERMINOLOGY', 'Denomination Terminology Updated'), ('DENOMINATION_SEEDS_CONFIG', 'Denomination Seed Config Updated'), ('DENOMINATION_BILLING_VIEW', 'Denomination Billing Viewed'), ('DENOMINATION_PURGE', 'Denomination Permanently Deleted'), ('AUDIT_EXPORT', 'Audit Log Exported'), ('OPS_EMAIL_TEST', 'Ops Email Test Sent'), ('IMPERSONATE_START', 'Impersonation Started'), ('IMPERSONATE_END', 'Impersonation Ended'), ('BREAKGLASS_GRANT', 'Break-glass Access Granted'), ('MEMBER_IMPORT', 'Member Bulk Import'), ('TRANSACTION_IMPORT', 'Receipt Bulk Import'), ('MARKETING_SETTINGS', 'Marketing Settings Updated'), ('MARKETING_CAMPAIGN_CREATE', 'Marketing Campaign Created'), ('MARKETING_CAMPAIGN_UPDATE', 'Marketing Campaign Updated'), ('MARKETING_CAMPAIGN_ARCHIVE', 'Marketing Campaign Archived'), ('MARKETING_LEAD_SUBMIT', 'Marketing Lead Submitted'), ('MARKETING_LEAD_UPDATE', 'Marketing Lead Updated'), ('MARKETING_ASSET_CREATE', 'Marketing Asset Created'), ('MARKETING_ASSET_UPDATE', 'Marketing Asset Updated'), ('MARKETING_ASSET_ARCHIVE', 'Marketing Asset Archived')], max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_ip_allowlist',
            field=models.TextField(blank=True, default='', help_text='Optional. Newline-separated public IPs allowed for /platform/. Empty = allow any IP (recommended when using MFA on a dynamic home ISP). Do not list residential IPs that change daily — use a static/VPN IP later if needed.'),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('medium', models.CharField(blank=True, max_length=80)),
                ('campaign_tag', models.CharField(blank=True, max_length=100)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], default='NEW', max_length=12)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_text', models.TextField()),
                ('consented_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_leads_assigned', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sitecontrol.marketingcampaign')),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_leads', to='sitecontrol.denomination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('BROCHURE', 'Brochure'), ('PRESENTATION', 'Presentation'), ('VIDEO', 'Video'), ('SCREENSHOT', 'Screenshot'), ('DATASHEET', 'Datasheet'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('public_url', models.URLField()),
                ('status', models.CharField(choices=[('INTERNAL', 'Internal'), ('REVIEW', 'Review Required'), ('APPROVED', 'Approved for External Use'), ('ARCHIVED', 'Archived')], default='REVIEW', max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_assets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['status', 'sort_order'], name='sitecontrol_status_4a80cb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['status', '-created_at'], name='sitecontrol_status_4feeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='marketinglead',
            index=models.Index(fields=['status', '-created_at'], name='sitecontrol_status_c038e3_idx'),
        ),
        migrations.AddIndex(
            model_name='marketinglead',
            index=models.Index(fields=['contact_email'], name='sitecontrol_contact_7cd01a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketinglead',
            index=models.Index(fields=['campaign', '-created_at'], name='sitecontrol_campaig_6c92da_idx'),
        ),
        migrations.AddIndex(
            model_name='marketinglead',
            index=models.Index(fields=['denomination', 'status'], name='sitecontrol_denomin_531381_idx'),
        ),
    ]
