# Generated by Django 5.1.15 on 2026-08-08 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0019_marketingsettings_alter_platformauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglead',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketinglead',
            name='anonymized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_leads_anonymized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketinglead',
            name='notification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketinglead',
            name='notification_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='marketinglead',
            name='notification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DISABLED', 'Disabled')], default='DISABLED', max_length=10),
        ),
        migrations.AddField(
            model_name='marketinglead',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingsettings',
            name='lead_retention_days',
            field=models.PositiveIntegerField(default=365, help_text='Closed leads older than this may be anonymized (30–2555 days).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(2555)]),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SETTINGS_UPDATE', 'Settings Updated'), ('PLAN_UPDATE', 'Plan Updated'), ('SUBSCRIPTION_UPDATE', 'Subscription Updated'), ('SUBSCRIPTION_PAYMENT', 'Subscription Payment Recorded'), ('TENANT_UPDATE', 'Tenant Updated'), ('TENANT_SUSPEND', 'Tenant Suspended'), ('TENANT_REACTIVATE', 'Tenant Reactivated'), ('TENANT_OFFBOARD', 'Tenant Offboarded'), ('OPERATOR_CREATE', 'Platform Operator Created'), ('OPERATOR_UPDATE', 'Platform Operator Updated'), ('OPERATOR_DEACTIVATE', 'Platform Operator Deactivated'), ('ANNOUNCEMENT_UPDATE', 'Announcement Updated'), ('FEATURE_UPDATE', 'Feature Registry Updated'), ('MAINTENANCE_TOGGLE', 'Maintenance Mode Toggled'), ('REGISTRATION_UPDATE', 'Registration Settings Updated'), ('APPLICATION_SUBMIT', 'Tenant Application Submitted'), ('APPLICATION_APPROVE', 'Tenant Application Approved'), ('APPLICATION_REJECT', 'Tenant Application Rejected'), ('TENANT_PROVISION', 'Tenant Provisioned'), ('TENANT_REPROVISION', 'Tenant Financials Re-provisioned'), ('PAYMENT_METHOD_UPDATE', 'Payment Method Updated'), ('SUBSCRIPTIONS_EXPIRED', 'Subscriptions Expired (batch)'), ('DENOMINATION_CREATE', 'Denomination Created'), ('DENOMINATION_UPDATE', 'Denomination Updated'), ('DENOMINATION_SEED', 'Denomination Profiles Seeded'), ('DENOMINATION_TERMINOLOGY', 'Denomination Terminology Updated'), ('DENOMINATION_SEEDS_CONFIG', 'Denomination Seed Config Updated'), ('DENOMINATION_BILLING_VIEW', 'Denomination Billing Viewed'), ('DENOMINATION_PURGE', 'Denomination Permanently Deleted'), ('AUDIT_EXPORT', 'Audit Log Exported'), ('OPS_EMAIL_TEST', 'Ops Email Test Sent'), ('IMPERSONATE_START', 'Impersonation Started'), ('IMPERSONATE_END', 'Impersonation Ended'), ('BREAKGLASS_GRANT', 'Break-glass Access Granted'), ('MEMBER_IMPORT', 'Member Bulk Import'), ('TRANSACTION_IMPORT', 'Receipt Bulk Import'), ('MARKETING_SETTINGS', 'Marketing Settings Updated'), ('MARKETING_CAMPAIGN_CREATE', 'Marketing Campaign Created'), ('MARKETING_CAMPAIGN_UPDATE', 'Marketing Campaign Updated'), ('MARKETING_CAMPAIGN_ARCHIVE', 'Marketing Campaign Archived'), ('MARKETING_LEAD_SUBMIT', 'Marketing Lead Submitted'), ('MARKETING_LEAD_UPDATE', 'Marketing Lead Updated'), ('MARKETING_ASSET_CREATE', 'Marketing Asset Created'), ('MARKETING_ASSET_UPDATE', 'Marketing Asset Updated'), ('MARKETING_ASSET_ARCHIVE', 'Marketing Asset Archived'), ('MARKETING_LEAD_NOTIFY', 'Marketing Lead Notification Updated'), ('MARKETING_LEAD_EXPORT', 'Marketing Leads Exported'), ('MARKETING_LEAD_ANONYMIZE', 'Marketing Lead Anonymized')], max_length=40),
        ),
    ]
