# Generated by Django 5.1.15 on 2026-08-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontrol', '0020_marketinglead_anonymized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='allow_institution_branding',
            field=models.BooleanField(default=True, help_text='Allow institution Super Admins to update logo and brand colors.'),
        ),
    ]
