# Generated by Django 5.1.15 on 2026-08-31 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_church_history_entry'),
        ('sitecontrol', '0022_public_demo_trials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SETTINGS_UPDATE', 'Settings Updated'), ('PLAN_UPDATE', 'Plan Updated'), ('SUBSCRIPTION_UPDATE', 'Subscription Updated'), ('SUBSCRIPTION_PAYMENT', 'Subscription Payment Recorded'), ('TENANT_UPDATE', 'Tenant Updated'), ('TENANT_SUSPEND', 'Tenant Suspended'), ('TENANT_REACTIVATE', 'Tenant Reactivated'), ('TENANT_OFFBOARD', 'Tenant Offboarded'), ('OPERATOR_CREATE', 'Platform Operator Created'), ('OPERATOR_UPDATE', 'Platform Operator Updated'), ('OPERATOR_DEACTIVATE', 'Platform Operator Deactivated'), ('ANNOUNCEMENT_UPDATE', 'Announcement Updated'), ('FEATURE_UPDATE', 'Feature Registry Updated'), ('MAINTENANCE_TOGGLE', 'Maintenance Mode Toggled'), ('REGISTRATION_UPDATE', 'Registration Settings Updated'), ('APPLICATION_SUBMIT', 'Tenant Application Submitted'), ('APPLICATION_APPROVE', 'Tenant Application Approved'), ('APPLICATION_REJECT', 'Tenant Application Rejected'), ('TENANT_PROVISION', 'Tenant Provisioned'), ('TENANT_REPROVISION', 'Tenant Financials Re-provisioned'), ('PAYMENT_METHOD_UPDATE', 'Payment Method Updated'), ('SUBSCRIPTIONS_EXPIRED', 'Subscriptions Expired (batch)'), ('DENOMINATION_CREATE', 'Denomination Created'), ('DENOMINATION_UPDATE', 'Denomination Updated'), ('DENOMINATION_SEED', 'Denomination Profiles Seeded'), ('DENOMINATION_TERMINOLOGY', 'Denomination Terminology Updated'), ('DENOMINATION_SEEDS_CONFIG', 'Denomination Seed Config Updated'), ('DENOMINATION_BILLING_VIEW', 'Denomination Billing Viewed'), ('DENOMINATION_PURGE', 'Denomination Permanently Deleted'), ('AUDIT_EXPORT', 'Audit Log Exported'), ('OPS_EMAIL_TEST', 'Ops Email Test Sent'), ('IMPERSONATE_START', 'Impersonation Started'), ('IMPERSONATE_END', 'Impersonation Ended'), ('BREAKGLASS_GRANT', 'Break-glass Access Granted'), ('MEMBER_IMPORT', 'Member Bulk Import'), ('TRANSACTION_IMPORT', 'Receipt Bulk Import'), ('MARKETING_SETTINGS', 'Marketing Settings Updated'), ('MARKETING_CAMPAIGN_CREATE', 'Marketing Campaign Created'), ('MARKETING_CAMPAIGN_UPDATE', 'Marketing Campaign Updated'), ('MARKETING_CAMPAIGN_ARCHIVE', 'Marketing Campaign Archived'), ('MARKETING_LEAD_SUBMIT', 'Marketing Lead Submitted'), ('MARKETING_LEAD_UPDATE', 'Marketing Lead Updated'), ('MARKETING_ASSET_CREATE', 'Marketing Asset Created'), ('MARKETING_ASSET_UPDATE', 'Marketing Asset Updated'), ('MARKETING_ASSET_ARCHIVE', 'Marketing Asset Archived'), ('MARKETING_LEAD_NOTIFY', 'Marketing Lead Notification Updated'), ('MARKETING_LEAD_EXPORT', 'Marketing Leads Exported'), ('MARKETING_LEAD_ANONYMIZE', 'Marketing Lead Anonymized'), ('ACTIVATION_REQUEST', 'Full Version Activation Requested')], max_length=40),
        ),
        migrations.CreateModel(
            name='SubscriptionActivationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('ACTIVATED', 'Activated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('church_name', models.CharField(max_length=200)),
                ('church_code', models.CharField(blank=True, max_length=20)),
                ('church_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('payment_reference', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='organization.church')),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_requests', to='sitecontrol.denomination')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_requests', to='sitecontrol.tenantsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sitecontrol_status_525d2a_idx'), models.Index(fields=['church', 'status'], name='sitecontrol_church__fba789_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('church',), name='uniq_pending_activation_per_church')],
            },
        ),
    ]
