# Generated by Django 5.1.15 on 2026-09-02 14:53

import sitecontrol.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_church_history_entry'),
        ('sitecontrol', '0023_subscription_activation_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionactivationrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionactivationrequest',
            name='billing_interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionactivationrequest',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='subscriptionactivationrequest',
            name='payment_reference_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptionactivationrequest',
            name='plan_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='subscriptionactivationrequest',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=sitecontrol.models.activation_receipt_upload_to),
        ),
        migrations.AddIndex(
            model_name='subscriptionactivationrequest',
            index=models.Index(fields=['payment_reference_normalized'], name='sitecontrol_payment_7f9981_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionactivationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACKNOWLEDGED', 'ACTIVATED']), models.Q(('payment_reference_normalized', ''), _negated=True)), fields=('payment_reference_normalized',), name='uniq_activation_payment_ref_active'),
        ),
    ]
