# Generated by Django 5.1.15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontrol", "0024_activation_request_billing_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionactivationrequest",
            name="requested_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activation_requests",
                to="sitecontrol.subscriptionplan",
            ),
        ),
    ]
