# Generated by Django 5.1.15

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontrol", "0025_activation_request_requested_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="denomination",
            name="money_decimal_places",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="How many decimal places to show for money on dashboards and reports (0–4). Ledgers still post with standard rounding.",
                validators=[MinValueValidator(0), MaxValueValidator(4)],
            ),
        ),
        migrations.AddField(
            model_name="denomination",
            name="notification_retention_read_days",
            field=models.PositiveSmallIntegerField(
                default=90,
                help_text="Purge read in-app notifications older than this many days.",
                validators=[MinValueValidator(7), MaxValueValidator(730)],
            ),
        ),
        migrations.AddField(
            model_name="denomination",
            name="notification_retention_unread_days",
            field=models.PositiveSmallIntegerField(
                default=180,
                help_text="Purge unread in-app notifications older than this many days.",
                validators=[MinValueValidator(14), MaxValueValidator(1095)],
            ),
        ),
    ]
