# Generated by Django 6.0.6 on 2026-07-04 18:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_leadershiprole_spiritualgift_memberspiritualgift'),
        ('organization', '0002_generalconference_union_conference_union'),
        ('transactions', '0007_payroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('is_statutory', models.BooleanField(default=False)),
                ('calculation_method', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENT_GROSS', 'Percent of Gross'), ('PERCENT_BASIC', 'Percent of Basic'), ('COMPUTED', 'Computed (Statutory)')], default='FIXED', max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_types', to='organization.church')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('host_church', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paying_unit_type', models.CharField(choices=[('CHURCH', 'Church'), ('DISTRICT', 'District'), ('CONFERENCE', 'Conference'), ('UNION', 'Union'), ('GENERAL_CONFERENCE', 'General Conference')], default='CHURCH', max_length=30)),
                ('paying_unit_id', models.UUIDField(db_index=True)),
                ('employee_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('STIPEND', 'Stipend'), ('VOLUNTEER_ALLOWANCE', 'Volunteer Allowance')], default='FULL_TIME', max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('tin_encrypted', models.TextField(blank=True)),
                ('ssnit_number_encrypted', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_account_encrypted', models.TextField(blank=True)),
                ('date_joined', models.DateField()),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='members.department')),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.church')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='members.member')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='payroll.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_recovery', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid Off'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayComponentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_components', to='organization.church')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.employeecompensation')),
                ('deduction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_lines', to='payroll.deductiontype')),
                ('pay_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_lines', to='payroll.paycomponenttype')),
            ],
            options={
                'ordering': ['line_type', 'pay_component__sort_order', 'deduction_type__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_in_period', models.PositiveSmallIntegerField(default=30)),
                ('days_worked', models.PositiveSmallIntegerField(default=30)),
                ('is_pro_rata', models.BooleanField(default=False)),
                ('payslip_number', models.CharField(blank=True, max_length=40)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.employee')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER', 'Employer Contribution')], max_length=10)),
                ('code', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payroll_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollline')),
            ],
            options={
                'ordering': ['item_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('paying_unit_type', models.CharField(choices=[('CHURCH', 'Church'), ('DISTRICT', 'District'), ('CONFERENCE', 'Conference'), ('UNION', 'Union'), ('GENERAL_CONFERENCE', 'General Conference')], default='CHURCH', max_length=30)),
                ('paying_unit_id', models.UUIDField(db_index=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('pay_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organization.church')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='transactions.transaction')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_prepared', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payrollline',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='PayrollRunAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('CALCULATE', 'Calculated'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('POST', 'Posted'), ('PAY', 'Paid'), ('VOID', 'Voided')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.payrollrun')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard PAYE', max_length=100)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_tax_tables', to='organization.church')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('tax_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='payroll.payrolltaxtable')),
            ],
            options={
                'ordering': ['sort_order', 'lower_limit'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryContributionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('applies_to', models.CharField(choices=[('BASIC', 'Basic Salary'), ('GROSS', 'Gross Taxable')], default='BASIC', max_length=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_rules', to='organization.church')),
            ],
            options={
                'ordering': ['code', '-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['host_church', 'status'], name='payroll_emp_host_ch_a62c17_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['paying_unit_type', 'paying_unit_id'], name='payroll_emp_paying__a7e09e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('host_church', 'employee_number')},
        ),
        migrations.AlterUniqueTogether(
            name='paycomponenttype',
            unique_together={('host_church', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('host_church', 'paying_unit_type', 'paying_unit_id', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollline',
            unique_together={('payroll_run', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='statutorycontributionrule',
            unique_together={('host_church', 'code', 'effective_from')},
        ),
    ]
