# Generated by Django 5.1.15 on 2026-07-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcements_enterprise'),
        ('members', '0008_member_portal_email_unique_and_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='Optional UserRole codes. Empty = all roles in scope.'),
        ),
        migrations.CreateModel(
            name='AnnouncementDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_department_links', to='announcements.announcement')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='members.department')),
            ],
            options={
                'unique_together': {('announcement', 'department')},
            },
        ),
    ]
