# Generated by Django 5.1.15 on 2026-09-14 12:14

import announcements.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_denomination'),
        ('members', '0009_alter_member_date_of_birth'),
        ('organization', '0006_church_history_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ARCHIVE', 'Archive'), ('PIN', 'Pin'), ('UNPIN', 'Unpin'), ('EXPORT', 'Export'), ('BIRTHDAY_PREP', 'Birthday flyer prepared'), ('BIRTHDAY_GET', 'Birthday flyer downloaded'), ('BIRTHDAY_POST', 'Birthday marked posted')], max_length=20),
        ),
        migrations.CreateModel(
            name='BirthdayWishDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('flyer', models.ImageField(blank=True, upload_to=announcements.models.birthday_flyer_upload_to)),
                ('caption', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PREPARED', 'Prepared'), ('DOWNLOADED', 'Downloaded'), ('POSTED', 'Posted')], default='PREPARED', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_wish_dispatches', to='organization.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_flyers_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_wish_dispatches', to='members.member')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_flyers_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrence_date', 'member__last_name'],
                'indexes': [models.Index(fields=['church', 'occurrence_date'], name='bday_wish_church_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('church', 'member', 'occurrence_date'), name='uniq_birthday_wish_church_member_day')],
            },
        ),
    ]
