# Generated by Django 5.1.15 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_birthdaywishdispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ARCHIVE', 'Archive'), ('PIN', 'Pin'), ('UNPIN', 'Unpin'), ('EXPORT', 'Export'), ('BIRTHDAY_PREP', 'Birthday flyer prepared'), ('BIRTHDAY_GET', 'Birthday flyer downloaded'), ('BIRTHDAY_POST', 'Birthday marked posted'), ('BIRTHDAY_CAP', 'Birthday caption saved')], max_length=20),
        ),
    ]
