# Generated by Django 5.1.15 on 2026-09-14 13:31

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_member_birthday_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaywishdispatch',
            name='flyer_story',
            field=models.ImageField(blank=True, upload_to=announcements.models.birthday_story_upload_to),
        ),
    ]
