from django.urls import path

from . import views

app_name = "members"

urlpatterns = [
    path("", views.MemberListView.as_view(), name="list"),
    path("api/search/", views.member_search, name="search"),
    path("add/", views.add, name="add"),
    path("visitors/", views.visitor_list, name="visitor_list"),
    path("visitors/add/", views.visitor_add, name="visitor_add"),
    path("visitors/<uuid:pk>/edit/", views.visitor_edit, name="visitor_edit"),
    path("visitors/<uuid:pk>/convert/", views.visitor_convert, name="visitor_convert"),
    path("<uuid:member_id>/", views.member_detail, name="detail"),
    path("<uuid:member_id>/export/", views.member_export, name="member_export"),
    path("edit/<uuid:member_id>/", views.edit, name="edit"),
    path("timeline/<uuid:member_id>/", views.member_timeline, name="timeline"),
    path("records/", views.record_list, name="record_list"),
    path("records/add/", views.record_add, name="record_add"),
    path("records/<int:pk>/", views.record_detail, name="record_detail"),
    path("records/<int:pk>/edit/", views.record_edit, name="record_edit"),
    path("departments/", views.department_list, name="department_list"),
    path("departments/add/", views.department_add, name="department_add"),
    path("departments/<uuid:pk>/edit/", views.department_edit, name="department_edit"),
    path("departments/<uuid:pk>/delete/", views.department_delete, name="department_delete"),
    path("families/", views.family_list, name="family_list"),
    path("families/add/", views.family_add, name="family_add"),
    path("families/<uuid:pk>/", views.family_detail, name="family_detail"),
    path("families/<uuid:pk>/edit/", views.family_edit, name="family_edit"),
    path("transfers/", views.transfer_list, name="transfer_list"),
    path("transfers/add/", views.transfer_create, name="transfer_create"),
    path("transfers/<uuid:pk>/", views.transfer_detail, name="transfer_detail"),
    path("baptisms/", views.baptism_register, name="baptism_register"),
    path("leadership/", views.leadership_list, name="leadership_list"),
    path("leadership/add/", views.leadership_add, name="leadership_add"),
    path("leadership/<uuid:pk>/end/", views.leadership_end, name="leadership_end"),
    path("spiritual-gifts/", views.spiritual_gift_list, name="spiritual_gift_list"),
    path("spiritual-gifts/add/", views.spiritual_gift_add, name="spiritual_gift_add"),
    path("<uuid:member_id>/assign-gift/", views.member_assign_gift, name="assign_gift"),
    path(
        "<uuid:member_id>/gifts/<uuid:assignment_id>/remove/",
        views.member_unassign_gift,
        name="unassign_gift",
    ),
    path("configuration/", views.configuration_hub, name="configuration"),
    path("configuration/occupations/", views.occupation_list, name="occupation_list"),
    path("configuration/occupations/add/", views.occupation_add, name="occupation_add"),
    path("configuration/occupations/<int:pk>/edit/", views.occupation_edit, name="occupation_edit"),
    path("configuration/occupations/<int:pk>/delete/", views.occupation_delete, name="occupation_delete"),
    path("configuration/lists/", views.member_lookup_list, name="member_lookup_list"),
    path("configuration/lists/add/", views.member_lookup_edit, name="member_lookup_add"),
    path("configuration/lists/<uuid:pk>/edit/", views.member_lookup_edit, name="member_lookup_edit"),
]
