# Generated by Django 6.0.6 on 2026-07-04 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.church')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.department'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='organization.church')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_head', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ['name'],
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.family'),
        ),
        migrations.CreateModel(
            name='MemberTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='organization.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='members.member')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='organization.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
