# Generated by Django 6.0.6 on 2026-07-04 02:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_department_member_department_family_member_family_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_roles', to='organization.church')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_roles', to='members.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_roles', to='members.member')),
            ],
            options={
                'ordering': ['-is_active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_gifts', to='organization.church')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MemberSpiritualGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noted_at', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_gift_assignments', to='members.member')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='members.spiritualgift')),
            ],
            options={
                'unique_together': {('member', 'gift')},
            },
        ),
    ]
