# Generated by Django 6.0.6 on 2026-07-09 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def clear_duplicate_member_phones(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    seen = {}
    for member in Member.objects.exclude(phone="").order_by("created_at", "id"):
        key = (str(member.church_id), (member.phone or "").strip())
        if not key[1]:
            continue
        if key in seen:
            member.phone = ""
            member.save(update_fields=["phone"])
        else:
            seen[key] = member.pk


def clear_duplicate_membership_numbers(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    seen = {}
    for member in Member.objects.exclude(membership_number="").order_by("created_at", "id"):
        key = (str(member.church_id), (member.membership_number or "").strip())
        if not key[1]:
            continue
        if key in seen:
            member.membership_number = ""
            member.save(update_fields=["membership_number"])
        else:
            seen[key] = member.pk


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_leadershiprole_spiritualgift_memberspiritualgift"),
        ("organization", "0005_backfill_financials_provisioned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("STATUS", "Status Change"),
                            ("TRANSFER_REQUEST", "Transfer Request"),
                            ("TRANSFER_COMPLETE", "Transfer Complete"),
                            ("TRANSFER_REJECT", "Transfer Reject"),
                            ("EXPORT", "Export"),
                            ("DEACTIVATE", "Deactivate"),
                            ("ACTIVATE", "Activate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="occupation",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="member",
            name="baptism_certificate_number",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="member",
            name="baptism_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="baptism_place",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Widowed", "Widowed"),
                    ("Divorced", "Divorced"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="record",
            name="certificate_number",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="record",
            name="officiant",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="record",
            name="place",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="occupation",
            unique_together={("church", "name")},
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["church", "membership_status"], name="members_mem_church__3459e6_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["church", "last_name", "first_name"], name="members_mem_church__1af643_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["church", "phone"], name="members_mem_church__645b58_idx"),
        ),
        migrations.AddIndex(
            model_name="membertransfer",
            index=models.Index(fields=["status", "created_at"], name="members_mem_status_35c84a_idx"),
        ),
        migrations.AddIndex(
            model_name="membertransfer",
            index=models.Index(fields=["from_church", "status"], name="members_mem_from_ch_bd6b25_idx"),
        ),
        migrations.AddIndex(
            model_name="membertransfer",
            index=models.Index(fields=["to_church", "status"], name="members_mem_to_chur_130147_idx"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["church", "record_type", "event_date"], name="members_rec_church__a0ad4d_idx"),
        ),
        migrations.RunPython(clear_duplicate_member_phones, migrations.RunPython.noop),
        migrations.RunPython(clear_duplicate_membership_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("church", "phone"),
                name="uniq_member_phone_per_church",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("membership_number", ""), _negated=True),
                fields=("church", "membership_number"),
                name="uniq_member_number_per_church",
            ),
        ),
        migrations.AddField(
            model_name="memberauditlog",
            name="church",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_audit_logs",
                to="organization.church",
            ),
        ),
        migrations.AddField(
            model_name="memberauditlog",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="memberauditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="memberauditlog",
            index=models.Index(fields=["church", "created_at"], name="members_mem_church__afba14_idx"),
        ),
        migrations.AddIndex(
            model_name="memberauditlog",
            index=models.Index(fields=["member", "created_at"], name="members_mem_member__09332c_idx"),
        ),
    ]
