# Generated by Django 5.1.15 on 2026-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('STATUS', 'Status Change'), ('TRANSFER_REQUEST', 'Transfer Request'), ('TRANSFER_COMPLETE', 'Transfer Complete'), ('TRANSFER_REJECT', 'Transfer Reject'), ('EXPORT', 'Export'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('DEPARTMENT_DELETE', 'Department Deleted'), ('GIFT_UNASSIGN', 'Spiritual Gift Unassigned')], max_length=30),
        ),
    ]
