# Generated by Django 5.1.15 on 2026-07-23 18:18

import uuid
from django.db import migrations, models


def seed_member_lookups(apps, schema_editor):
    MemberLookupOption = apps.get_model("members", "MemberLookupOption")
    seeds = [
        ("gender", [("Male", "Male"), ("Female", "Female")]),
        (
            "marital_status",
            [
                ("Single", "Single"),
                ("Married", "Married"),
                ("Widowed", "Widowed"),
                ("Divorced", "Divorced"),
            ],
        ),
        (
            "membership_status",
            [
                ("Active", "Active"),
                ("Inactive", "Inactive"),
                ("Transferred", "Transferred"),
                ("Deceased", "Deceased"),
            ],
        ),
        (
            "record_type",
            [
                ("Baptism", "Baptism"),
                ("Marriage", "Marriage"),
                ("Funeral", "Funeral"),
                ("Meeting", "Meeting"),
                ("Transfer", "Transfer"),
                ("Other", "Other"),
            ],
        ),
        ("record_status", [("Active", "Active"), ("Archived", "Archived")]),
    ]
    for category, choices in seeds:
        for order, (code, label) in enumerate(choices):
            MemberLookupOption.objects.get_or_create(
                category=category,
                code=code,
                defaults={
                    "label": label,
                    "is_active": True,
                    "is_system": True,
                    "sort_order": order * 10,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rc1_consistency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='MemberLookupOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('record_type', 'Record type'), ('record_status', 'Record status'), ('membership_status', 'Membership status'), ('gender', 'Gender'), ('marital_status', 'Marital status')], max_length=40)),
                ('code', models.CharField(help_text='Stored value on member/record rows. Prefer stable codes.', max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded option — code cannot be deleted.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member lookup option',
                'verbose_name_plural': 'Member lookup options',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.RunPython(seed_member_lookups, migrations.RunPython.noop),
    ]
