# Generated by Django 5.1.15 on 2026-07-23 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_status_and_migrate_history(apps, schema_editor):
    MemberLookupOption = apps.get_model("members", "MemberLookupOption")
    History = apps.get_model("members", "History")
    Record = apps.get_model("members", "Record")

    extras = [
        ("Missing", "Missing", 40),
        ("Suspended", "Suspended", 50),
        ("Former Member", "Former Member", 60),
    ]
    for code, label, order in extras:
        MemberLookupOption.objects.get_or_create(
            category="membership_status",
            code=code,
            defaults={
                "label": label,
                "is_active": True,
                "is_system": True,
                "sort_order": order,
            },
        )

    for hist in History.objects.all().iterator():
        if Record.objects.filter(migrated_from_history_id=hist.pk).exists():
            continue
        Record.objects.create(
            church_id=hist.church_id,
            member_id=hist.member_id,
            record_type="Other",
            status="Active",
            title=hist.title,
            description=hist.description or "",
            event_date=hist.date,
            migrated_from_history_id=hist.pk,
            created_by_id=hist.created_by_id,
            is_deleted=False,
            deletion_reason="",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_lookups_and_flexible_choices'),
        ('organization', '0005_backfill_financials_provisioned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('visit_date', models.DateField()),
                ('interests', models.CharField(blank=True, default='', max_length=255)),
                ('follow_up_status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='uniq_member_phone_per_church',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='uniq_member_number_per_church',
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='family',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='family',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadershiprole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadershiprole',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadershiprole',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leadershiprole',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='family_relationship',
            field=models.CharField(blank=True, default='', help_text='Role within the household when a family is assigned.', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='migrated_from_history_id',
            field=models.PositiveIntegerField(blank=True, help_text='Set when converted from legacy History rows.', null=True),
        ),
        migrations.AddField(
            model_name='spiritualgift',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spiritualgift',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spiritualgift',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='spiritualgift',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='memberauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('STATUS', 'Status Change'), ('TRANSFER_REQUEST', 'Transfer Request'), ('TRANSFER_COMPLETE', 'Transfer Complete'), ('TRANSFER_REJECT', 'Transfer Reject'), ('EXPORT', 'Export'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore'), ('DEPARTMENT_CREATE', 'Department Created'), ('DEPARTMENT_UPDATE', 'Department Updated'), ('DEPARTMENT_DELETE', 'Department Deleted'), ('FAMILY_CREATE', 'Family Created'), ('FAMILY_UPDATE', 'Family Updated'), ('RECORD_CREATE', 'Record Created'), ('RECORD_UPDATE', 'Record Updated'), ('LEADERSHIP_ASSIGN', 'Leadership Assigned'), ('LEADERSHIP_END', 'Leadership Ended'), ('GIFT_ASSIGN', 'Spiritual Gift Assigned'), ('GIFT_UNASSIGN', 'Spiritual Gift Unassigned'), ('GIFT_CATALOG_CREATE', 'Spiritual Gift Catalog Created'), ('VISITOR_CREATE', 'Visitor Created'), ('VISITOR_UPDATE', 'Visitor Updated'), ('VISITOR_CONVERT', 'Visitor Converted')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'is_deleted'], name='members_mem_church__839ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['church', 'is_deleted'], name='members_rec_church__aee762_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('phone', ''), _negated=True), ('is_deleted', False)), fields=('church', 'phone'), name='uniq_member_phone_per_church'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('membership_number', ''), _negated=True), ('is_deleted', False)), fields=('church', 'membership_number'), name='uniq_member_number_per_church'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='assigned_elder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_assigned', to='members.member'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='organization.church'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='converted_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_visitor', to='members.member'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_invited', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['church', 'visit_date'], name='members_vis_church__de332d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['church', 'follow_up_status'], name='members_vis_church__6739bd_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['church', 'is_deleted'], name='members_vis_church__49dee4_idx'),
        ),
        migrations.RunPython(seed_status_and_migrate_history, migrations.RunPython.noop),
    ]
