# Generated by Django 5.1.15 on 2026-07-23 22:18

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def clear_duplicate_member_emails(apps, schema_editor):
    """Keep the oldest active member email; clear later duplicates so the unique constraint can apply."""
    Member = apps.get_model("members", "Member")
    seen = {}
    qs = (
        Member.objects.exclude(email="")
        .filter(is_deleted=False)
        .order_by("created_at", "id")
    )
    for member in qs.iterator():
        key = (member.email or "").strip().lower()
        if not key:
            continue
        if key in seen:
            member.email = ""
            member.save(update_fields=["email"])
        else:
            seen[key] = member.pk


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_enterprise_members_phases"),
        ("organization", "0005_backfill_financials_provisioned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Required when an email is set (used for member portal first sign-in).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Must be unique when set. Used as the member portal username.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="memberauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("STATUS", "Status Change"),
                    ("TRANSFER_REQUEST", "Transfer Request"),
                    ("TRANSFER_COMPLETE", "Transfer Complete"),
                    ("TRANSFER_REJECT", "Transfer Reject"),
                    ("EXPORT", "Export"),
                    ("DEACTIVATE", "Deactivate"),
                    ("ACTIVATE", "Activate"),
                    ("SOFT_DELETE", "Soft Delete"),
                    ("RESTORE", "Restore"),
                    ("DEPARTMENT_CREATE", "Department Created"),
                    ("DEPARTMENT_UPDATE", "Department Updated"),
                    ("DEPARTMENT_DELETE", "Department Deleted"),
                    ("FAMILY_CREATE", "Family Created"),
                    ("FAMILY_UPDATE", "Family Updated"),
                    ("RECORD_CREATE", "Record Created"),
                    ("RECORD_UPDATE", "Record Updated"),
                    ("LEADERSHIP_ASSIGN", "Leadership Assigned"),
                    ("LEADERSHIP_END", "Leadership Ended"),
                    ("GIFT_ASSIGN", "Spiritual Gift Assigned"),
                    ("GIFT_UNASSIGN", "Spiritual Gift Unassigned"),
                    ("GIFT_CATALOG_CREATE", "Spiritual Gift Catalog Created"),
                    ("VISITOR_CREATE", "Visitor Created"),
                    ("VISITOR_UPDATE", "Visitor Updated"),
                    ("VISITOR_CONVERT", "Visitor Converted"),
                    ("OCCUPATION_CREATE", "Occupation Created"),
                    ("OCCUPATION_UPDATE", "Occupation Updated"),
                    ("OCCUPATION_DELETE", "Occupation Deleted"),
                    ("LOOKUP_CREATE", "Lookup Option Created"),
                    ("LOOKUP_UPDATE", "Lookup Option Updated"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(clear_duplicate_member_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(
                    models.Q(("email", ""), _negated=True),
                    ("is_deleted", False),
                ),
                name="uniq_member_email_active_ci",
            ),
        ),
    ]
