# Generated by Django 5.1.15 on 2026-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_portal_email_unique_and_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required when an email is set.', null=True),
        ),
    ]
