# Generated by Django 5.1.15 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allow_birthday_photo',
            field=models.BooleanField(default=True, help_text="Use this member's photo on church birthday flyers when a picture is on file."),
        ),
        migrations.AddField(
            model_name='member',
            name='hide_public_birthday',
            field=models.BooleanField(default=False, help_text='Do not list this member on the birthday flyer desk or communications calendar.'),
        ),
    ]
