# Generated by Django 5.1.15 on 2026-09-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_member_birthday_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="allow_birthday_photo",
            field=models.BooleanField(
                default=False,
                help_text="Use this member's photo on church birthday flyers only with explicit consent.",
            ),
        ),
    ]
